// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220201211438_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Client1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Client2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Client3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Client4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Client5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Client6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Client7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Client8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Client9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Client10"
                        },
                        new
                        {
                            ClientId = 11,
                            Name = "Client11"
                        },
                        new
                        {
                            ClientId = 12,
                            Name = "Client12"
                        },
                        new
                        {
                            ClientId = 13,
                            Name = "Client13"
                        },
                        new
                        {
                            ClientId = 14,
                            Name = "Client14"
                        },
                        new
                        {
                            ClientId = 15,
                            Name = "Client15"
                        },
                        new
                        {
                            ClientId = 16,
                            Name = "Client16"
                        },
                        new
                        {
                            ClientId = 17,
                            Name = "Client17"
                        },
                        new
                        {
                            ClientId = 18,
                            Name = "Client18"
                        },
                        new
                        {
                            ClientId = 19,
                            Name = "Client19"
                        },
                        new
                        {
                            ClientId = 20,
                            Name = "Client20"
                        },
                        new
                        {
                            ClientId = 21,
                            Name = "Client21"
                        },
                        new
                        {
                            ClientId = 22,
                            Name = "Client22"
                        },
                        new
                        {
                            ClientId = 23,
                            Name = "Client23"
                        },
                        new
                        {
                            ClientId = 24,
                            Name = "Client24"
                        },
                        new
                        {
                            ClientId = 25,
                            Name = "Client25"
                        },
                        new
                        {
                            ClientId = 26,
                            Name = "Client26"
                        },
                        new
                        {
                            ClientId = 27,
                            Name = "Client27"
                        },
                        new
                        {
                            ClientId = 28,
                            Name = "Client28"
                        },
                        new
                        {
                            ClientId = 29,
                            Name = "Client29"
                        },
                        new
                        {
                            ClientId = 30,
                            Name = "Client30"
                        },
                        new
                        {
                            ClientId = 31,
                            Name = "Client31"
                        },
                        new
                        {
                            ClientId = 32,
                            Name = "Client32"
                        },
                        new
                        {
                            ClientId = 33,
                            Name = "Client33"
                        },
                        new
                        {
                            ClientId = 34,
                            Name = "Client34"
                        },
                        new
                        {
                            ClientId = 35,
                            Name = "Client35"
                        },
                        new
                        {
                            ClientId = 36,
                            Name = "Client36"
                        },
                        new
                        {
                            ClientId = 37,
                            Name = "Client37"
                        },
                        new
                        {
                            ClientId = 38,
                            Name = "Client38"
                        },
                        new
                        {
                            ClientId = 39,
                            Name = "Client39"
                        },
                        new
                        {
                            ClientId = 40,
                            Name = "Client40"
                        },
                        new
                        {
                            ClientId = 41,
                            Name = "Client41"
                        },
                        new
                        {
                            ClientId = 42,
                            Name = "Client42"
                        },
                        new
                        {
                            ClientId = 43,
                            Name = "Client43"
                        },
                        new
                        {
                            ClientId = 44,
                            Name = "Client44"
                        },
                        new
                        {
                            ClientId = 45,
                            Name = "Client45"
                        },
                        new
                        {
                            ClientId = 46,
                            Name = "Client46"
                        },
                        new
                        {
                            ClientId = 47,
                            Name = "Client47"
                        },
                        new
                        {
                            ClientId = 48,
                            Name = "Client48"
                        },
                        new
                        {
                            ClientId = 49,
                            Name = "Client49"
                        },
                        new
                        {
                            ClientId = 50,
                            Name = "Client50"
                        },
                        new
                        {
                            ClientId = 51,
                            Name = "Client51"
                        },
                        new
                        {
                            ClientId = 52,
                            Name = "Client52"
                        },
                        new
                        {
                            ClientId = 53,
                            Name = "Client53"
                        },
                        new
                        {
                            ClientId = 54,
                            Name = "Client54"
                        },
                        new
                        {
                            ClientId = 55,
                            Name = "Client55"
                        },
                        new
                        {
                            ClientId = 56,
                            Name = "Client56"
                        },
                        new
                        {
                            ClientId = 57,
                            Name = "Client57"
                        },
                        new
                        {
                            ClientId = 58,
                            Name = "Client58"
                        },
                        new
                        {
                            ClientId = 59,
                            Name = "Client59"
                        },
                        new
                        {
                            ClientId = 60,
                            Name = "Client60"
                        },
                        new
                        {
                            ClientId = 61,
                            Name = "Client61"
                        },
                        new
                        {
                            ClientId = 62,
                            Name = "Client62"
                        },
                        new
                        {
                            ClientId = 63,
                            Name = "Client63"
                        },
                        new
                        {
                            ClientId = 64,
                            Name = "Client64"
                        },
                        new
                        {
                            ClientId = 65,
                            Name = "Client65"
                        },
                        new
                        {
                            ClientId = 66,
                            Name = "Client66"
                        },
                        new
                        {
                            ClientId = 67,
                            Name = "Client67"
                        },
                        new
                        {
                            ClientId = 68,
                            Name = "Client68"
                        },
                        new
                        {
                            ClientId = 69,
                            Name = "Client69"
                        },
                        new
                        {
                            ClientId = 70,
                            Name = "Client70"
                        },
                        new
                        {
                            ClientId = 71,
                            Name = "Client71"
                        },
                        new
                        {
                            ClientId = 72,
                            Name = "Client72"
                        },
                        new
                        {
                            ClientId = 73,
                            Name = "Client73"
                        },
                        new
                        {
                            ClientId = 74,
                            Name = "Client74"
                        },
                        new
                        {
                            ClientId = 75,
                            Name = "Client75"
                        },
                        new
                        {
                            ClientId = 76,
                            Name = "Client76"
                        },
                        new
                        {
                            ClientId = 77,
                            Name = "Client77"
                        },
                        new
                        {
                            ClientId = 78,
                            Name = "Client78"
                        },
                        new
                        {
                            ClientId = 79,
                            Name = "Client79"
                        },
                        new
                        {
                            ClientId = 80,
                            Name = "Client80"
                        },
                        new
                        {
                            ClientId = 81,
                            Name = "Client81"
                        },
                        new
                        {
                            ClientId = 82,
                            Name = "Client82"
                        },
                        new
                        {
                            ClientId = 83,
                            Name = "Client83"
                        },
                        new
                        {
                            ClientId = 84,
                            Name = "Client84"
                        },
                        new
                        {
                            ClientId = 85,
                            Name = "Client85"
                        },
                        new
                        {
                            ClientId = 86,
                            Name = "Client86"
                        },
                        new
                        {
                            ClientId = 87,
                            Name = "Client87"
                        },
                        new
                        {
                            ClientId = 88,
                            Name = "Client88"
                        },
                        new
                        {
                            ClientId = 89,
                            Name = "Client89"
                        },
                        new
                        {
                            ClientId = 90,
                            Name = "Client90"
                        },
                        new
                        {
                            ClientId = 91,
                            Name = "Client91"
                        },
                        new
                        {
                            ClientId = 92,
                            Name = "Client92"
                        },
                        new
                        {
                            ClientId = 93,
                            Name = "Client93"
                        },
                        new
                        {
                            ClientId = 94,
                            Name = "Client94"
                        },
                        new
                        {
                            ClientId = 95,
                            Name = "Client95"
                        },
                        new
                        {
                            ClientId = 96,
                            Name = "Client96"
                        },
                        new
                        {
                            ClientId = 97,
                            Name = "Client97"
                        },
                        new
                        {
                            ClientId = 98,
                            Name = "Client98"
                        },
                        new
                        {
                            ClientId = 99,
                            Name = "Client99"
                        },
                        new
                        {
                            ClientId = 100,
                            Name = "Client100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
