// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for Product 1",
                            Name = "Product1",
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for Product 2",
                            Name = "Product2",
                            Price = 351m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for Product 3",
                            Name = "Product3",
                            Price = 508m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for Product 4",
                            Name = "Product4",
                            Price = 368m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for Product 5",
                            Name = "Product5",
                            Price = 493m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for Product 6",
                            Name = "Product6",
                            Price = 876m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for Product 7",
                            Name = "Product7",
                            Price = 929m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for Product 8",
                            Name = "Product8",
                            Price = 754m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for Product 9",
                            Name = "Product9",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for Product 10",
                            Name = "Product10",
                            Price = 382m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for Product 11",
                            Name = "Product11",
                            Price = 259m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for Product 12",
                            Name = "Product12",
                            Price = 145m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for Product 13",
                            Name = "Product13",
                            Price = 640m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for Product 14",
                            Name = "Product14",
                            Price = 149m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for Product 15",
                            Name = "Product15",
                            Price = 623m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for Product 16",
                            Name = "Product16",
                            Price = 295m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for Product 17",
                            Name = "Product17",
                            Price = 265m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for Product 18",
                            Name = "Product18",
                            Price = 764m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for Product 19",
                            Name = "Product19",
                            Price = 725m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for Product 20",
                            Name = "Product20",
                            Price = 575m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for Product 21",
                            Name = "Product21",
                            Price = 104m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for Product 22",
                            Name = "Product22",
                            Price = 893m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for Product 23",
                            Name = "Product23",
                            Price = 503m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for Product 24",
                            Name = "Product24",
                            Price = 650m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for Product 25",
                            Name = "Product25",
                            Price = 203m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for Product 26",
                            Name = "Product26",
                            Price = 962m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for Product 27",
                            Name = "Product27",
                            Price = 705m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for Product 28",
                            Name = "Product28",
                            Price = 537m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for Product 29",
                            Name = "Product29",
                            Price = 351m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for Product 30",
                            Name = "Product30",
                            Price = 295m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for Product 31",
                            Name = "Product31",
                            Price = 770m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for Product 32",
                            Name = "Product32",
                            Price = 824m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for Product 33",
                            Name = "Product33",
                            Price = 194m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for Product 34",
                            Name = "Product34",
                            Price = 395m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for Product 35",
                            Name = "Product35",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for Product 36",
                            Name = "Product36",
                            Price = 975m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for Product 37",
                            Name = "Product37",
                            Price = 494m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for Product 38",
                            Name = "Product38",
                            Price = 295m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for Product 39",
                            Name = "Product39",
                            Price = 388m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for Product 40",
                            Name = "Product40",
                            Price = 963m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for Product 41",
                            Name = "Product41",
                            Price = 431m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for Product 42",
                            Name = "Product42",
                            Price = 764m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for Product 43",
                            Name = "Product43",
                            Price = 986m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for Product 44",
                            Name = "Product44",
                            Price = 552m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for Product 45",
                            Name = "Product45",
                            Price = 153m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for Product 46",
                            Name = "Product46",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for Product 47",
                            Name = "Product47",
                            Price = 218m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for Product 48",
                            Name = "Product48",
                            Price = 205m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for Product 49",
                            Name = "Product49",
                            Price = 625m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for Product 50",
                            Name = "Product50",
                            Price = 160m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for Product 51",
                            Name = "Product51",
                            Price = 565m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for Product 52",
                            Name = "Product52",
                            Price = 313m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for Product 53",
                            Name = "Product53",
                            Price = 286m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for Product 54",
                            Name = "Product54",
                            Price = 416m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for Product 55",
                            Name = "Product55",
                            Price = 853m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for Product 56",
                            Name = "Product56",
                            Price = 587m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for Product 57",
                            Name = "Product57",
                            Price = 848m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for Product 58",
                            Name = "Product58",
                            Price = 858m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for Product 59",
                            Name = "Product59",
                            Price = 264m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for Product 60",
                            Name = "Product60",
                            Price = 530m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for Product 61",
                            Name = "Product61",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for Product 62",
                            Name = "Product62",
                            Price = 491m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for Product 63",
                            Name = "Product63",
                            Price = 503m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for Product 64",
                            Name = "Product64",
                            Price = 860m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for Product 65",
                            Name = "Product65",
                            Price = 611m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for Product 66",
                            Name = "Product66",
                            Price = 435m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for Product 67",
                            Name = "Product67",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for Product 68",
                            Name = "Product68",
                            Price = 345m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for Product 69",
                            Name = "Product69",
                            Price = 992m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for Product 70",
                            Name = "Product70",
                            Price = 647m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for Product 71",
                            Name = "Product71",
                            Price = 801m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for Product 72",
                            Name = "Product72",
                            Price = 969m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for Product 73",
                            Name = "Product73",
                            Price = 475m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for Product 74",
                            Name = "Product74",
                            Price = 761m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for Product 75",
                            Name = "Product75",
                            Price = 244m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for Product 76",
                            Name = "Product76",
                            Price = 340m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for Product 77",
                            Name = "Product77",
                            Price = 907m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for Product 78",
                            Name = "Product78",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for Product 79",
                            Name = "Product79",
                            Price = 596m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for Product 80",
                            Name = "Product80",
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for Product 81",
                            Name = "Product81",
                            Price = 844m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for Product 82",
                            Name = "Product82",
                            Price = 599m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for Product 83",
                            Name = "Product83",
                            Price = 911m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for Product 84",
                            Name = "Product84",
                            Price = 290m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for Product 85",
                            Name = "Product85",
                            Price = 730m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for Product 86",
                            Name = "Product86",
                            Price = 557m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for Product 87",
                            Name = "Product87",
                            Price = 638m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for Product 88",
                            Name = "Product88",
                            Price = 778m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for Product 89",
                            Name = "Product89",
                            Price = 541m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for Product 90",
                            Name = "Product90",
                            Price = 569m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for Product 91",
                            Name = "Product91",
                            Price = 227m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for Product 92",
                            Name = "Product92",
                            Price = 636m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for Product 93",
                            Name = "Product93",
                            Price = 130m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for Product 94",
                            Name = "Product94",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for Product 95",
                            Name = "Product95",
                            Price = 792m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for Product 96",
                            Name = "Product96",
                            Price = 939m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for Product 97",
                            Name = "Product97",
                            Price = 360m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for Product 98",
                            Name = "Product98",
                            Price = 225m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for Product 99",
                            Name = "Product99",
                            Price = 941m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for Product 100",
                            Name = "Product100",
                            Price = 718m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 17
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
